<?php


$customer_id = $_REQUEST['customer_id'];

require_once dirname(__DIR__, 2) . '/controller/CTRLModalSearchForAdmin.php';

$instanceOfModalSearchForAdmin = new CTRLModalSearchForAdmin('bonds_and_guarantee', 'loans', 'overdraft_register', 'all_branches');

$method_for_search_admin = $instanceOfModalSearchForAdmin->search_facility_details($customer_id);

//$records = json_decode($method_for_search_admin);

$records = $method_for_search_admin['general_array_for_all_records'];

?>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title mb-0">Facilities Associated with this Collateral</h5>
            </div>
            <div class="card-body">
                <table id="modal_data_table" class="display table buttons-datatables table-responsive modal_data_table" style="width:100%">
                    <thead>
                        <tr>
                            <th>Facility Type</th>
                            <th>Customer Name</th>
                            <th>Account Number</th>
                            <th>Customer ID</th>
                            <th>Amount</th>
                            <th>Currency</th>
                            <th>Branch</th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php
                        foreach ($records as $cll) {
                        ?>

                            <tr>
                                <td><?php echo $cll['facility_type']; ?></td>
                                <td><?php echo $cll['customer_name']; ?></td>
                                <td><?php echo $cll['account_number']; ?></td>
                                <td><?php echo $cll['customer_id']; ?></td>
                                <td><?php echo $cll['amount']; ?></td>
                                <td><?php echo $cll['currency']; ?></td>
                                <td><?php echo $cll['branch_name']; ?></td>
                            </tr>

                        <?php
                        }
                        ?>

                </table>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#modal_data_table').DataTable({
            dom: "Bfrtip",

            buttons: ["copy", "csv", "excel", "print"],

            responsive: {
                details: {
                    display: $.fn.dataTable.Responsive.display.modal({
                        header: function(row) {
                            var data = row.data();
                            return 'Details for ' + data[0] + ' ' + data[1];
                        }
                    }),
                    renderer: $.fn.dataTable.Responsive.renderer.tableAll({
                        tableClass: 'table'
                    })
                }
            }
        });
    });
    
</script>