<?php

$classification = $_REQUEST['id'];

$classification = $_REQUEST['id'];

switch ($classification) {

    case 1:
        $classification = 'NORM';
        break;

    case 2:
        $classification = 'OLEM';
        break;

    case 3:
        $classification = 'SUBT';
        break;

    case 4:
        $classification = 'DOUBT';
        break;

    case 5:
        $classification = 'LOSS';
        break;

    default:
        'Unknown';
}

require_once dirname(__DIR__, 2) . '/controller/CTRLGetBranchesForModal.php';

$instanceOfBranchModalSearch = new CTRLGetBranchesForModal('all_branches');

$method_for_search_branches = $instanceOfBranchModalSearch->get_branches_for_modal();

?>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title mb-0">Collateral By Branches- <?php echo $classification; ?></h5>
            </div>
            <div class="card-body">

                <form action="" method="post" name="check_collateral_by_branches" class="form-horizontal form" id="check_collateral_by_branches" autocomplete="off">
                    <div class="row">
                        <div class="col-lg-3">
                            <label for="client_list" class="form-label"></label>
                            <select class="form-select mb-3" aria-label="Default select example" id="branch_code" name="branch_code">
                                <option selected>Select a Branch </option>

                                <?php

                                foreach ($method_for_search_branches as $brn) {
                                ?>
                                    <option value="<?php echo $brn['branch_code']; ?>"><?php echo $brn['branch_name']; ?></option>

                                <?php
                                }

                                ?>
                            </select>
                        </div>

                        <div class="col-lg-2">
                            <label for="filter_end_date" class="form-label"></label>
                            <input class="form-control" type="hidden" id="classification" value="<?php echo $classification; ?>" name="classification" />
                            <button class="btn btn-danger w-100" style="padding-top: 18px;" type="submit" id="filterBtn" name="filterBtn">Search</button>
                        </div>

                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">

            <div id="branches_response_here"></div>

            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#modal_data_table').DataTable({
            dom: "Bfrtip",

            buttons: ["copy", "csv", "excel", "print"],

            initComplete: function() {
                // Apply the search
                this.api()
                    .columns()
                    .every(function() {
                        var that = this;

                        $('input', this.footer()).on('keyup change clear', function() {
                            if (that.search() !== this.value) {
                                that.search(this.value).draw();
                            }
                        });
                    });
            },

            responsive: {
                details: {
                    display: $.fn.dataTable.Responsive.display.modal({
                        header: function(row) {
                            var data = row.data();
                            return 'Details for ' + data[0] + ' ' + data[1];
                        }
                    }),
                    renderer: $.fn.dataTable.Responsive.renderer.tableAll({
                        tableClass: 'table'
                    })
                }
            }
        });

        document.addEventListener("DOMContentLoaded", function() {
            new DataTable("#ajax-datatables", {
                ajax: "../assets/json/datatable.json"
            });
        });

        $("#modal_data_table tfoot th").each(function() {
            var title = $(this).text();
            $(this).html('<input type="text" placeholder="Search ' + title + '" />');
        });

    });
</script>

<script>
    $("#check_collateral_by_branches").on("submit", function(e) {

        e.preventDefault();

        let branch_code = $('#branch_code').val();
        let classification = $('#classification').val();

        $.ajax({
            url: "apps/dashboard/controller/CTRLGetCollateralsByBranch.php",
            method: "POST",

            //dataType: "JSON",
            data: {
                branch_code: branch_code, classification: classification
            },
            // cache: false,
            //processData: false,
            success: function(data) {
                $("#branches_response_here").html(data);

            },
        });

    });
</script>